Traceback (most recent call last):
  File "c:\users\wai\appdata\local\programs\python\python37\lib\site-packages\jupyter_cache\executors\utils.py", line 64, in single_nb_execution
    **kwargs,
  File "c:\users\wai\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\wai\appdata\local\programs\python\python37\lib\site-packages\jupyter_core\utils\__init__.py", line 98, in wrapped
    return loop.run_until_complete(inner)
  File "c:\users\wai\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\wai\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 706, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\wai\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\wai\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from IPython.display import display, Markdown

train = pd.read_csv('./files/train.csv')
train
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_12980\3484458488.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mimport[0m [0mpandas[0m [1;32mas[0m [0mpd[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;32mimport[0m [0mmatplotlib[0m[1;33m.[0m[0mpyplot[0m [1;32mas[0m [0mplt[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [1;32mfrom[0m [0msklearn[0m[1;33m.[0m[0mlinear_model[0m [1;32mimport[0m [0mLinearRegression[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;32mfrom[0m [0mIPython[0m[1;33m.[0m[0mdisplay[0m [1;32mimport[0m [0mdisplay[0m[1;33m,[0m [0mMarkdown[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'pandas'

